alias rgcpp='rg -t cpp'
alias rgcmake='rg -t cmake'
alias hist='history | tail -50'
alias attach='tmux -CC new -A -s'
alias fixssh='export SSH_AUTH_SOCK=$(ls -t /tmp/ssh-**/* | head -1)'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gf='git fetch'
alias gp='git pull'
